#!/bin/bash

middleman build
rm -Rf ../../public/*
rm -Rf ../../src/gratefulplace/templates/*
cp -R build/* ../../public

# todo more intelligently move directories
mv ../../public/{*.html,users,posts} ../../src/gratefulplace/templates

